# Generated by Django 5.1 on 2024-08-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_phone',
            field=models.IntegerField(blank=True, max_length=14, null=True),
        ),
    ]
