# Generated by Django 5.1 on 2024-08-27 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_number_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number_phone',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono solo puede contener hasta 14 dígitos.', regex='^\\d{1,14}$')]),
        ),
    ]
