# Generated by Django 5.1 on 2024-09-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActuProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('progreso', models.IntegerField(default=0)),
            ],
        ),
    ]
