# Generated by Django 5.1 on 2024-09-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_actuproyecto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActuProyecto',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='progreso',
            field=models.IntegerField(default=0),
        ),
    ]
