# Generated by Django 5.1 on 2024-09-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_roles_archivos_comentarios_miembrosproyectos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Archivos',
        ),
        migrations.DeleteModel(
            name='Comentarios',
        ),
    ]
