# Generated by Django 5.1 on 2024-09-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
       ('user', '0009_remove_comentarios_proyecto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='nombre',
        ),
        migrations.AddField(
            model_name='roles',
            name='rol',
            field=models.CharField(choices=[('Administrador del departamento', 'Administrador del departamento'), ('Tutor', 'Tutor'), ('Asistente', 'Asistente'), ('Superadmin', 'Superadmin')], default='Tutor', max_length=50),
        ),
    ]
